spring.application.name=CustomerRoute

#MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}


#ARTEMIS
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=${ARTEMIS_USER}
spring.artemis.password=${ARTEMIS_PASSWORD}


#MESSAGE ENDPOINTS
inbound.endpoint-uri=file:messages/in?include=.*\\.json&readLock=changed
outbound.endpoint-uri=jms:queue:messages-out
