CREATE TABLE tiers (
     id SMALLINT PRIMARY KEY AUTO_INCREMENT,
     tier_name VARCHAR(50) UNIQUE NOT NULL,
     discount_percentage SMALLINT NOT NULL
);

CREATE TABLE customer (
    customer_id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    tier_id SMALLINT NOT NULL,

    FOREIGN KEY (tier_id) REFERENCES tiers(id)
);

